version: "1"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx.development.dockerfile
    depends_on:
      - voucher
    ports:
      - "80:80"
      - "443:443"
    networks:
      - voucher-network

  voucher:
    container_name: Voucher-Service
    build:
      context: .
      dockerfile: ./docker/voucher.node.development.dockerfile
    ports:
      - "3010:3010"
    volumes:
      - .:/var/www/voucher
    depends_on:
      - voucherdb
    networks:
      voucher-network:
        ipv4_address: 172.28.0.14
        aliases:
          - voucher.local

  voucherdb:
    container_name: voucherdb
    restart: always
    image: mysql:latest
    volumes:
      - "mysql:/var/lib/mysql"
      - "./config/mysql/sql.cnf:/etc/mysql/conf.d/sql.cnf"
    ports:
      - "3367:3306"
    env_file:
      - ./docker/env/voucherdb.development.env
    networks:
      voucher-network:
        ipv4_address: 172.28.0.15
        aliases:
          - voucherdb.local

volumes:
  mysql:
  servers:

networks:
  voucher-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16